### PR TITLE
Cancellation fixes

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by ares** [comment]
@j00bar could you pretty please take a quick look if something looks off? If not, ACK would be appreciated.

**Comment by j00bar** [comment]
LGTM.

Curious why, if you're defining constants with string values on `ResponseQueue`, that you're leaving constants in the function for `cancel_run`?

**Comment by adamruzicka** [comment]
Don't recall if there ever was a valid reason for that, fixed

**Comment by j00bar** [comment]
:+1:

**Pull request merged**
