### PR TITLE
GH #2 - Check given input values for sanity

### PR DESCRIPTION
**Pull request by adamruzicka**
This commit brings sanity checking for configuration given by receptor
to the plugin for a run to make the plugin more robust. If a a
configuration value does not pass the checks, a warning is logged and
default value is used instead.

This also checks if hostnames contain a comma, such hostnames not sent
over to Satellite are marked as failed straight away.

### CODE REVIEW

**Comment by adamruzicka** [comment]
@cedricbu could you take a look?

**Comment by ares** [comment]
@j00bar could you pretty please take a quick look if something looks off? If not, ACK would be appreciated.

**Comment by j00bar** [comment]
LGTM.

My only suggestion would be that in your `validate` function, include logic that checks to see if the given values is `None` and therefore just returns `default_value`, which will simplify `validate_input`; no need to get-and-set-with-default before you call `validate` on each value, as you can just `.get()` the entries from `raw` as part of your call to `validate`. Does that make sense?

**Comment by j00bar** [comment]
:+1:

**Comment by adamruzicka** [comment]
Thank you @j00bar for the review

**Pull request merged**
